### ISSUE TITLE
Parameterless Constructor Error

### ISSUE THREAD

**Issue by LBobirca** [webadvanced/Structuremap.WebAPI2#8]
I'm getting an error about the controller needing a parameterless public constructor. I've double checked the setup instructions and can't find where I've gone wrong.  Any help would be appreciated.

<error>
<message>An error has occurred.</message>
<exceptionmessage>An error occurred when trying to create a controller of type 'EventsController'. Make sure that the controller has a parameterless public constructor.</exceptionmessage>
<exceptiontype>System.InvalidOperationException</exceptiontype>
<stacktrace>at System.Web.Http.Dispatcher.DefaultHttpControllerActivator.Create(HttpRequestMessage request, HttpControllerDescriptor controllerDescriptor, Type controllerType)
at System.Web.Http.Controllers.HttpControllerDescriptor.CreateController(HttpRequestMessage request)
at System.Web.Http.Dispatcher.HttpControllerDispatcher.&lt;SendAsync&gt;d__1.MoveNext()</stacktrace>
<innerexception>
<message>An error has occurred.</message>
<exceptionmessage>Type 'EventViewpoint_SinglePage.Controllers.EventsController' does not have a default constructor</exceptionmessage>
<exceptiontype>System.ArgumentException</exceptiontype>
<stacktrace>at System.Linq.Expressions.Expression.New(Type type)
at System.Web.Http.Internal.TypeActivator.Create[TBase](Type instanceType)
at System.Web.Http.Dispatcher.DefaultHttpControllerActivator.GetInstanceOrActivator(HttpRequestMessage request, Type controllerType, Func`1& activator)
at System.Web.Http.Dispatcher.DefaultHttpControllerActivator.Create(HttpRequestMessage request, HttpControllerDescriptor controllerDescriptor, Type controllerType)</stacktrace>
</innerexception>
</error>

Thanks,
Luisz

**Comment by LBobirca** [comment]
This is not an issue with Structuremap.WebAPI2.  I figured this out.  In my startup I was creating a new HttpConfiguration rather than using the GlobalConfiguration.Configuration.  After that it was smooth sailing.  Sorry for the confusion, but hopefully it will help someone else that has the same issue.
